# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2a6b427336bb56389444b79997d42a379c21e4021041e5c349c13a15e83779e3d1f24392ae0d0b3085290bd52c31dae0310db428c2276a29622f32252bf1d1e

test:
  secret_key_base: 1b01aa43ab907b4de3f84a0d8cf92c203d65d29904307efa215c8ce741aaa25ebf9a19b7a97f4680f2171c565159820ab5ff17ec17fc7e76c84b8d7d5795f246

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
